#!/bin/bash
readonly VER='0.0.3'
readonly CREATE_YEAR='2019'
readonly AUTHOR='haruna <github.com/eggplants>'
readonly DEFAULT_YEAR=`date +%Y`
readonly DEFAULT_LINE='12'
readonly ANIMALS_EMOJI=(
    🐒 🐔 🐕 🐗 🐁 🐄
    🐯 🐇 🐲 🐍 🐎 🐏
)
readonly ANIMALS_KANJI=(
    申 酉 戌 亥 子 丑
    寅 卯 辰 巳 午 羊
)
# help
function show_help(){
cat<<EOS
NAME:
    etoyear - show eto-year list

USAGE:
    etoyear [option -h,-v,-k] [year (should >0)(default:${DEFAULT_YEAR})] [num of displayline(s) (should >0)(default:${DEFAULT_LINE})]

EXAMPLE:
    etoyear             : show list from this year to the next ${DEFAULT_LINE} years in emoji
    etoyear -k 1999 100 : show list from 1999 to the next 100 years in kanji

VERSION:
    etoyear version ${VER}
    Copyright (c) ${CREATE_YEAR} ${AUTHOR}
    Released under the MIT License.

OPTION:
   -h, --help    : show help
   -v, --version : show version
   -k, --kanji   : show animal(s) in kanji
EOS
}
# version
function show_version(){
cat<<EOS
etoyear version ${VER}
Copyright (c) ${CREATE_YEAR} ${AUTHOR}
Released under the MIT License.
EOS
}

# main
function main(){
# prosess options(help, version, kanji)
case "$1" in

-h|--help)
    show_help; exit 0;;
-v|--version)
    show_version; exit 0;;
-k|--kanji)
    local _animals=("${ANIMALS_KANJI[@]}"); shift;;
-*)
    echo "ARGUMENT_ERROR::invalid option:$1." 1>&2;exit 1;;
*)
    local _animals=("${ANIMALS_EMOJI[@]}");;

esac

if [[ "$#" = 0 ]];then
    if [[ "${_animals[0]}" == "申" ]];then
        main -k ${DEFAULT_YEAR} ${DEFAULT_LINE}
    else
	main ${DEFAULT_YEAR} ${DEFAULT_LINE}
    fi
    exit 0
fi

local _year="$1" _times="$(($2-1))"

if [[ "$1" -le 0 ]];then
    echo 'ARGUMENT_ERROR::first argument should be more than 0.' 1>&2;exit 1
fi

if [[ "$#" = 1 ]];then
    _times=$((${DEFAULT_LINE}-1))
elif [[ "$2" -le 0 ]];then
    echo 'ARGUMENT_ERROR::second argument should be more than 0.' 1>&2;exit 1
fi

local _ind=$((${_year}%12))

for i in `seq 0 ${_times}`;do
    echo ${_animals[$(((${_ind}+$i)%12))]}
done|nl -n ln -s' ' -v "${_year}"
}
main $@
exit $?
